changelog:
  exclude:
    labels:
      - build
      - github_actions
  categories:
    - title: Features
      labels:
        - enhancement
        - feature request
        - performance
    - title: Bug fixes
      labels:
        - bug
        - bug in dependency
        - regression
    - title: Dependency updates
      labels:
        - dependencies
        - library-update
        - sbt-plugin-update
    - title: Miscellaneous
      labels:
        - '*'
