build:
  image: olafurpg/scalafix:0.0.1
  commands:
    # This machine has lots of ram and the tests on this need it.
    - echo "-Xmx55g" >> .jvmopts
    - echo "-Xms10g" >> .jvmopts
    - echo "-XX:ReservedCodeCacheSize=1000M" >> .jvmopts
    # configuring ivy.home doesn't seem to work. Maybe related:
    #   https://github.com/sbt/sbt/issues/1894
    # After 10+ experiments I've given up on trying to use sbt.ivy.yhome and
    # copy the files myself instead, as recommended here:
    #   http://readme.drone.io/usage/caching/
    - test -d /drone/.sbt && cp -a /drone/.sbt /root
    - rm -rf /drone/.sbt

    - test -d /drone/.ivy2 && cp -a /drone/.ivy2 /root
    - rm -rf /drone/.ivy2

    - ./bin/testAll.sh

    - cp -a /root/.ivy2 /drone
    - cp -a /root/.sbt /drone
cache:
  mount:
    - /drone/.sbt
    - /drone/.ivy2
    - /drone/cache

