name: CI
on:
  push:
    branches:
      - main
    tags_ignore:
      - '*'
  pull_request:

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        java:
          - '11'
          - '21'
        os:
          - windows-2025
          - ubuntu-22.04
        scala:
          - '2.12.20'
          - '2.13.16'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Set up JVM
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'sbt'
      - uses: sbt/setup-sbt@v1
      - name: Set git config for GitOps tests
        id: gitconfig
        run: git config --global user.email "scalafmt@scalameta.org" && git config --global user.name "scalafmt"
#      - run: sbt -debug -DlogLevel=debug ++${{ matrix.scala }} test-native
      - run: sbt -DlogLevel=debug ++${{ matrix.scala }} test-native
        if: ${{ (success() || failure()) && steps.gitconfig.outcome == 'success' }}
